const produse = [
    {
        name : "Placa Video MSI GeForce GTX 1050 Ti 4gb 256-bit",
        productType : "GPU",
        images : [
            "url",
            "url",
            "url",
        ],
        model : "GTX 1050Ti",
        launchDate : "2015",
        price : "300$",
        warranty : "36 months",
        interface : "PCI Express x16 4.0",
        maxResolution : "7680x4320",
        edition : "Gaming/X",
        series : "1000",
        graficProcessor : "Intel",
        boostClock : "12800",
        numberTransistor : "16800",
        cudaCores : "8",
        memoryType : "GDDR6",
        memory : "4gb",
        ports : "HDMI, VGA, DVI",
        coolingSystem : "Active, nxCoolers",
        dimensions : "197x108x35",
    },
    
    {
        name : "Placa Video Emtec GeForce GTX 1060 Ti 6gb 256-bit",
        productType : "GPU",
        images : [
            "url",
            "url",
            "url",
        ],
        model : "GTX 1060Ti",
        launchDate : "2015",
        price : "450$",
        warranty : "36 months",
        interface : "PCI Express x16 4.0",
        maxResolution : "7680x4320",
        edition : "Gaming/X",
        series : "1000",
        graficProcessor : "Intel",
        boostClock : "2100",
        numberTransistor : "20981",
        cudaCores : "12",
        memoryType : "GDDR6",
        memory : "6gb",
        ports : "HDMI, VGA, DVI",
        coolingSystem : "Active, 3xCoolers",
        dimensions : "197x108x35",
    },
    {
        name : "Placa Video GYGABYTE GeForce GTX 1080 Ti 12gb 256-bit",
        productType : "GPU",
        images : [
            "url",
            "url",
            "url",
        ],
        model : "GTX 1050Ti",
        launchDate : "2015",
        price : "800$",
        warranty : "36 months",
        interface : "PCI Express x16 4.0",
        maxResolution : "7680x4320",
        edition : "Gaming/X",
        series : "1000",
        graficProcessor : "Intel",
        boostClock : "28000",
        numberTransistor : "28780",
        cudaCores : "8",
        memoryType : "GDDR6",
        memory : "12gb",
        ports : "HDMI, VGA, DVI",
        coolingSystem : "Active, 3xCoolers",
        dimensions : "197x108x35",
    },
    {
        name : "Placa Video Asus GeForce GTX 1070 Ti 8gb 256-bit",
        productType : "GPU",
        images : [
            "url",
            "url",
            "url",
        ],
        model : "GTX 1050Ti",
        launchDate : "2015",
        price : "600$",
        warranty : "36 months",
        interface : "PCI Express x16 4.0",
        maxResolution : "7680x4320",
        edition : "Gaming/X",
        series : "1000",
        graficProcessor : "Intel",
        boostClock : "24000",
        numberTransistor : "23800",
        cudaCores : "16",
        memoryType : "GDDR6",
        memory : "8gb",
        ports : "HDMI, VGA, DVI",
        coolingSystem : "Active, 3xCoolers",
        dimensions : "197x108x35",
    },
    {
        name : "Placa Video Asus GeForce GTX 1660 Ti 8gb 256-bit",
        productType : "GPU",
        images : [
            "url",
            "url",
            "url",
        ],
        model : "GeForce 1660 Ti",
        launchDate : "2017",
        price : "500$",
        warranty : "36 months",
        interface : "PCI Express x16 4.0",
        maxResolution : "7680x4320",
        edition : "Gaming/X",
        series : "1600",
        graficProcessor : "Intel",
        boostClock : "17200",
        numberTransistor : "17241",
        cudaCores : "12",
        memoryType : "GDDR6",
        memory : "8gb",
        ports : "HDMI, VGA, DVI",
        coolingSystem : "Active, nxCoolers",
        dimensions : "197x108x35",
    },
    {
        name : "Placa Video GYGABYTE GeForce GTX 1650 Ti 4gb 256-bit",
        productType : "GPU",
        images : [
            "url",
            "url",
            "url",
        ],
        model : "GeForce 1660 Ti",
        launchDate : "2017",
        price : "380$",
        warranty : "36 months",
        interface : "PCI Express x16 4.0",
        maxResolution : "7680x4320",
        edition : "Gaming/X",
        series : "1600",
        graficProcessor : "Intel",
        boostClock : "12800",
        numberTransistor : "12810",
        cudaCores : "8",
        memoryType : "GDDR6",
        memory : "4gb",
        ports : "HDMI, VGA, DVI",
        coolingSystem : "Active, nxCoolers",
        dimensions : "197x108x35",
    },
    {
        name : " ",
        productType : "GPU",
        images : [
            "url",
            "url",
            "url",
        ],
        model : "",
        launchDate : "",
        price : "",
        warranty : "36 months",
        interface : "PCI Express x16 4.0",
        maxResolution : "7680x4320",
        edition : "Gaming/X",
        series : "1000",
        graficProcessor : "Intel",
        boostClock : "",
        numberTransistor : "16800",
        cudaCores : "8",
        memoryType : "GDDR6",
        memory : "",
        ports : "HDMI, VGA, DVI",
        coolingSystem : "Active, nxCoolers",
        dimensions : "197x108x35",
    },
    {
        name : "",
        productType : "GPU",
        images : [
            "url",
            "url",
            "url",
        ],
        model : "",
        launchDate : "",
        price : "",
        warranty : "36 months",
        interface : "PCI Express x16 4.0",
        maxResolution : "7680x4320",
        edition : "Gaming/X",
        series : "1000",
        graficProcessor : "Intel",
        boostClock : "",
        numberTransistor : "16800",
        cudaCores : "8",
        memoryType : "GDDR6",
        memory : "",
        ports : "HDMI, VGA, DVI",
        coolingSystem : "Active, nxCoolers",
        dimensions : "197x108x35",
    },
    {
        name : "",
        productType : "GPU",
        images : [
            "url",
            "url",
            "url",
        ],
        model : "",
        launchDate : "",
        price : "",
        warranty : "36 months",
        interface : "PCI Express x16 4.0",
        maxResolution : "7680x4320",
        edition : "Gaming/X",
        series : "1000",
        graficProcessor : "Intel",
        boostClock : "",
        numberTransistor : "16800",
        cudaCores : "8",
        memoryType : "GDDR6",
        memory : "",
        ports : "HDMI, VGA, DVI",
        coolingSystem : "Active, nxCoolers",
        dimensions : "197x108x35",
    },
    {
        name : "",
        productType : "GPU",
        images : [
            "url",
            "url",
            "url",
        ],
        model : "",
        launchDate : "",
        price : "",
        warranty : "36 months",
        interface : "PCI Express x16 4.0",
        maxResolution : "7680x4320",
        edition : "Gaming/X",
        series : "1000",
        graficProcessor : "Intel",
        boostClock : "",
        numberTransistor : "16800",
        cudaCores : "8",
        memoryType : "GDDR6",
        memory : "",
        ports : "HDMI, VGA, DVI",
        coolingSystem : "Active, nxCoolers",
        dimensions : "197x108x35",
    },
    {
        name : "",
        productType : "GPU",
        images : [
            "url",
            "url",
            "url",
        ],
        model : "",
        launchDate : "",
        price : "",
        warranty : "36 months",
        interface : "PCI Express x16 4.0",
        maxResolution : "7680x4320",
        edition : "Gaming/X",
        series : "1000",
        graficProcessor : "Intel",
        boostClock : "",
        numberTransistor : "16800",
        cudaCores : "8",
        memoryType : "GDDR6",
        memory : "",
        ports : "HDMI, VGA, DVI",
        coolingSystem : "Active, nxCoolers",
        dimensions : "197x108x35",
    },
    {
        name : "",
        productType : "GPU",
        images : [
            "url",
            "url",
            "url",
        ],
        model : "",
        launchDate : "",
        price : "",
        warranty : "36 months",
        interface : "PCI Express x16 4.0",
        maxResolution : "7680x4320",
        edition : "Gaming/X",
        series : "1000",
        graficProcessor : "Intel",
        boostClock : "",
        numberTransistor : "16800",
        cudaCores : "8",
        memoryType : "GDDR6",
        memory : "",
        ports : "HDMI, VGA, DVI",
        coolingSystem : "Active, 2xCoolers",
        dimensions : "197x108x35",
    },

    






]